### ISSUE TITLE
Czym używać ten skrypt?

### ISSUE THREAD

**Issue by BOSTON04** [TheRadziu/VODSubDL#2]
Witam
Wcześniej używałem skryptu zacnego do oglądania seriali z vod bez reklam. Skryptu używałem w rozszerzeniu do przeglądarki TamperMonkey ale teraz jak próbuje dodać ten skrypt TheRadzia pokazuje mi że błędny skrypt. Z tego co widzę to ten jest chyba napisany w innym języku programowania. Więc teraz czego najlepiej użyć aby skrypt działał?

**Comment by TheRadziu** [comment]
[Python](https://www.python.org/downloads/) w wersji 3.9 lub wyżej. 
Później w zależności od instalacji dwuklikiem na `VODSubDL.py` lub z linii komend `py VODSubDL.py`
