### ISSUE TITLE
Skrypt nie dziala, IDM nie widzi glownej aplikacji.

### ISSUE THREAD

**Issue by AlamarAFP** [TheRadziu/VODSubDL#3]
Witam, nie udaje sie mi uzyc tego sposobu, mam skrypt ktory eliminuje reklamy i dziala (ale nie na firefoxie) ale IDM nie chce dzialac/widziec 
glownej aplikacji ktora jest zainstalowana, a jesli chodzi o skrypt to poprzednia wersja niby sie uruchomiala (mam ostatniego pythona dla win7) ale nic i tak nie moglem z nim zrobic, teraz to uruchomienie sie nie udaje z cmd, w zalaczniku oba bledy https://imgur.com/a/6HB5Bxy PS - punkty sprawdzone, probowalem z wylaczonym firewallem i antywirem tez. Jaki inny program zamiast tego IDM zadziala ze skryptem np. na chrome? Darmowy XDM nie udalo mi sie powiazac z przegladarka.

**Comment by TheRadziu** [comment]
według screena twój plik ze skryptem jest uszkodzony, jego ostatnia część jest ucięta, tj; prawdopodobnie nie wszystko skopiowałes i wkleiłeś go do nowego pliku zamiast pobrać cały plik. 
Co do IDM'a to inna broszka, to zewnetrzny program i issues tego repo go nie pokrywa. Plugin integracyjny do przeglądarki nie ma nic wspólnego z nim, skrypt wysyła żądanie bezpośrednio do procesu IDM, a nie do przeglądarki

**Comment by AlamarAFP** [comment]
masz racje, teraz mam taki komunikat: "E:\Users\***\Downloads>py VODSubDL.py
Traceback (most recent call last):
  File "VODSubDL.py", line 21, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Pytane brzmi jak mam pobierac video z tego vod, wchodze przegladarka (juz bez pluginu intergracji) i odtwarzam ale idm i skrypt nic nie robia. Wpisanie linka do idm tez nic nie pobiera.

**Comment by AlamarAFP** [comment]
masz racje glupi blad, dzieki, udalo sie wreszcie i zaczelo pobierac, byla jeszcze potrzebna instalacja "pip" dla module request jak sie dowiedzialem od wujka google, pisze bo moze ktos bedzie tez potrzebowal, nie pamietam jaki komunikat mialem w poprzedniej wersji czy ten sam czy inny w kazdym razie idm juz pobiera, dzieki za swietny skrypt zwlaszcza (choc nie tylko) dla tak wolnego lacza jakie nadal zmuszony jestem posiadac jak znalazl.

**Comment by TheRadziu** [comment]
Szczerze to zapomniałem że `requests` jest dodatkowym modułem. Wieczorem przejrzę importy i dorzucę adekwatne requirements.txt i wtedy dopiero zamknę ten issue. Dzięki za informację.

**Comment by agxa-agxa** [comment]
Dzień dobry, od razu dziękuję za napisanie skryptu. Chciałabym zapytać czy mógłby mi ktoś po kolei wytłumaczyć jak i gdzie to zainstalować oraz jak pobierać materiał z vod?

**Comment by mr0czu** [comment]
Witam. Da radę przerobić by program korzystał z FDM? Bo próbowałem w zmianie ścieżek aplikacji itp. i nie działało. Pozdrawiam

**Comment by TheRadziu** [comment]
> Witam. Da radę przerobić by program korzystał z FDM? Bo próbowałem w zmianie ścieżek aplikacji itp. i nie działało. Pozdrawiam

jedyne co znalazłem o Free Download Manager tylko `fdm.exe "url.com/plik"` ale ma żadnego switcha do folderu do którego ma pobierać i pod jaką nazwą (video-9.mp4 za dużo raczej ci nie powie :P) ani żadnego silent mode żeby okienko nie wyskakiwało.  
Możesz to zastosować do notki numer jeden z readme.
