### ISSUE TITLE
Przestalo dzialac: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by AlamarAFP** [TheRadziu/VODSubDL#4]
Przestalo dzialac, taki blad: 
"Traceback (most recent call last):
  File "C:\Users\Alamar\VODSubDL.py", line 178, in <module>
    mkdir_p(name_and_dir(url, output_dir, False)[1])
  File "C:\Users\Alamar\VODSubDL.py", line 107, in name_and_dir
    nazwa_pliku = (tytul+" S"+f"{int(re.sub('[^0-9]', '', api_response['content'
]['info']['season'])):02d}"+"E"+f"{api_response['content']['info']['episode']:02
d}")
ValueError: invalid literal for int() with base 10: '' "

Natomiast najnowsza wersja nie uruchamia sie majac jakis problem z "xmltodict".

**Comment by TheRadziu** [comment]
rozwiąż najpierw 'jakiś problem z xmltodict', bo nie wspieram nieznanych poprzednich wersji skryptu.

Na najnowszej problem z niestandardową nazwą sezonu był dawno już naprawiony. 
Dla pewności podaj nazwę serialu, sezon i odcinek to się upewnię.

**Comment by AlamarAFP** [comment]
Zainstalowalem jak pisalo w google dwa kolejne moduly (xmltodict uaktualniajac krok po kroku pozniej jak nie dzialal tez pip i pip3 przez cmd oraz cpix) ktorych brak zglaszala nowa wersja, nic nie pomagalo, rezultatem na koncu jest ta sciana tekstu: 

  Running setup.py install for construct ... done
Successfully installed construct-2.10.68 cpix-1.3.0 isodate-0.6.1 lxml-4.9.2 pro
tobuf-4.21.12 pycryptodome-3.16.0 six-1.16.0

E:\Users\Alamar\Downloads>VODSubDL.py
Traceback (most recent call last):
  File "E:\Users\Alamar\Downloads\VODSubDL.py", line 34, in <module>
    from cpix.drm import widevine
  File "C:\Users\Alamar\AppData\Local\Programs\Python\Python38\lib\site-packages
\cpix\drm\widevine.py", line 11, in <module>
    from .widevine_pb2 import WidevineCencHeader
  File "C:\Users\Alamar\AppData\Local\Programs\Python\Python38\lib\site-packages
\cpix\drm\widevine_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "C:\Users\Alamar\AppData\Local\Programs\Python\Python38\lib\site-packages
\google\protobuf\descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and mu
st be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workaround
s are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Py
thon parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-
05-06#python-updates

Poprzednia wersja ktora do dzis uzywalem bez problemu czyli v2.29 nadal uruchamia sie ale nadal z tym samym bledem po podaniu url. Dla przypomnienia jak mam system windows 7 64.

**Comment by TheRadziu** [comment]
Błąd generuje zewnętrzny moduł, masz napisane mozliwe obejscia problemu, zamykam, niezwiązane ze skryptem.

**Comment by AlamarAFP** [comment]
Dzieki juz dziala, myslalem ze w czym innym problem ale poszedlem dalej
zgodnie z tym co pisalo (czyli downgrade do wersji 3.20 i jeszcze kolejny
modul, btw myslalem ze to nowe sa tylko opcjonalne do drm bbc). Niemniej
cos zmienili teraz bo przestala stara wersja dzialac. Dzieki za
pokierowanie i ponownie za skrypt, to moje pierwsze doswiadczenia z py.

Pozdro
Alamar
